Repository depromeet/mongsil-iOS, pull requests merged in 2022-06, with the labels that each got.

#67 refactor: login view
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Image/Buttons/AppleLoginButton.imageset/appleLoginButton.svg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Image/Buttons/KakaoLoginButton.imageset/kakaoLoginButton.svg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Background/BackgroundImage.imageset/Background Image.jpg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Background/BackgroundImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Background/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Background/ResultBackgroundImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Background/ResultBackgroundImage.imageset/ResultBackgroundImage.jpg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Buttons/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Buttons/KakaoLoginButton.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Buttons/KakaoLoginButton.imageset/KakaoLoginButton.svg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/CardResult/CardResultDefaultImage.imageset/CardResultDefaultImage.svg
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/CardResult/CardResultDefaultImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/CardResult/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/FirstOnboardingImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/FirstOnboardingImage.imageset/FirstOnboardingImage.png
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/SecondOnboardingImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/SecondOnboardingImage.imageset/SecondOnboardingImage.png
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/ThirdOnboardingImage.imageset/Contents.json
  Mongsil/Mongsil/Module/Component/Assets/Assets.xcassets/Images/OnboardingImage/ThirdOnboardingImage.imageset/ThirdOnboardingImage.png
  Mongsil/Mongsil/Module/Component/Assets/Images/Image+Generated.swift
  Mongsil/Mongsil/Module/Component/Models/Makers.swift
  Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
  Mongsil/Mongsil/Module/Feature/Login/LoginView.swift
  Mongsil/Mongsil/Module/Feature/Login/OnboardingImage.swift
  Mongsil/generated/R.generated.swift
Labels: ♻️refactor

#72 feat: Searchbar and Diary card alert modal
  Mongsil/Mongsil.xcodeproj/project.pbxproj
  Mongsil/Mongsil/Module/Component/Models/Diary.swift
  Mongsil/Mongsil/Module/Component/Views/AlertModal/AlertDoubleButton/AlertDoubleButtonCore.swift
  Mongsil/Mongsil/Module/Component/Views/AlertModal/AlertDoubleButton/AlertDoubleButtonView.swift
  Mongsil/Mongsil/Module/Component/Views/SearchBar/SearchBar.swift
  Mongsil/Mongsil/Module/Feature/Home/HomeView.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryView.swift
Labels: ⚡️feat, ♻️refactor

#73 fix: dropout logic call
  Mongsil/Mongsil/Application/AppCore.swift
Labels: 🔧fix

#74 feat: Apply UserCard API
  Mongsil/Mongsil.xcodeproj/project.pbxproj
  Mongsil/Mongsil/Module/Component/Models/Diary.swift
  Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
  Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/DeleteDiaryRequestDto.swift
  Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/EditDiaryRequestDto.swift
  Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/GetDiaryListRequestDto.swift
  Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/SaveDiaryRequestDto.swift
  Mongsil/Mongsil/Module/Component/Services/URL/URLHost.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryView.swift
Labels: ⚡️feat

#77 feat: Add App Uses Non-Exempt Encryption setting
  Mongsil/Mongsil/Info.plist
Labels: ⚡️feat

#79 docs: ReadMe
  README.md
Labels: 📜docs

#80 refactor: Fix SplashLogo
  Mongsil/Mongsil/Application/LaunchScreen.storyboard
  Mongsil/Mongsil/Assets.xcassets/SplashLogo.imageset/SplashLogo.svg
Labels: ♻️refactor

#81 feat: Add AppIcon
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/1024.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/114.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/120.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/180.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/29.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/40.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/57.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/58.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/60.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/80.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/87.png
  Mongsil/Mongsil/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mongsil/generated/R.generated.swift
Labels: ⚡️feat

#76 refactor: apply userCard api in core
  Mongsil/Mongsil.xcodeproj/project.pbxproj
  Mongsil/Mongsil/Application/AppCore.swift
  Mongsil/Mongsil/Application/SceneDelegate.swift
  Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
  Mongsil/Mongsil/Module/Component/Models/Diary.swift
  Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
  Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
  Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/DeleteDiaryRequestDto.swift
  Mongsil/Mongsil/Module/Component/Services/URL/URLHost.swift
  Mongsil/Mongsil/Module/Feature/Dream/DreamCore.swift
  Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
  Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryView.swift
  Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
  Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
Labels: ♻️refactor

#83 fix: add deleteToken in dropout service
  Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
  Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
Labels: 🔧fix
